In [38]:
import pandas as pd
data = pd.read_csv('data/train_set/2.data_add_feature1.csv', header = 0)
data.columns

Index(['방송일시', '노출(분)', '마더코드', '상품코드', '상품명', '상품군', '판매단가', '취급액', '휴일',
       'date', 'time', 'weekday', 'hour', '기온(°C)_seoul', '강수량(mm)_seoul',
       '습도(%)_seoul', '적설(cm)_seoul', '기온(°C)_busan', '강수량(mm)_busan',
       '습도(%)_busan', '적설(cm)_busan', 'pmWarning_seoul', 'pmWarning_busan',
       'quater'],
      dtype='object')

In [ ]:
## 1. 사용할 데이터만 가져오기

In [61]:
data_use = data.drop(columns = ['방송일시', '상품명', 'date','상품코드','마더코드','time'])
data_use_fit = data_use
data_use_fit

,노출(분),상품군,판매단가,취급액,휴일,weekday,hour,기온(°C)_seoul,강수량(mm)_seoul,습도(%)_seoul,적설(cm)_seoul,기온(°C)_busan,강수량(mm)_busan,습도(%)_busan,적설(cm)_busan,pmWarning_seoul,pmWarning_busan,quater
0,20.0,의류,39900,2099000.0,True,1,6,-7.9,0.0,60.0,0.0,-1.7,0.0,44.0,0.0,False,False,1
1,20.0,의류,39900,3262000.0,True,1,6,-7.9,0.0,60.0,0.0,-1.7,0.0,44.0,0.0,False,False,1
2,20.0,의류,39900,6672000.0,True,1,6,-7.9,0.0,60.0,0.0,-1.7,0.0,44.0,0.0,False,False,1
3,20.0,속옷,59000,6819000.0,True,1,7,-7.7,0.0,58.0,0.0,-1.8,0.0,49.0,0.0,False,False,1
4,20.0,속옷,59000,15689000.0,True,1,7,-7.7,0.0,58.0,0.0,-1.8,0.0,49.0,0.0,False,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37367,20.0,주방,158000,2328000.0,False,1,23,-7.4,0.0,45.0,0.0,-2.3,0.0,24.0,0.0,False,False,4
37368,20.0,주방,148000,10157000.0,False,1,23,-7.4,0.0,45.0,0.0,-2.3,0.0,24.0,0.0,False,False,4
37369,20.0,주방,168000,104392000.0,True,2,0,-6.5,0.0,38.0,0.0,-2.5,0.0,23.0,0.0,False,False,1
37370,20.0,주방,158000,13765000.0,True,2,0,-6.5,0.0,38.0,0.0,-2.5,0.0,23.0,0.0,False,False,1
37371,20.0,주방,148000,46608000.0,True,2,0,-6.5,0.0,38.0,0.0,-2.5,0.0,23.0,0.0,False,False,1

## 2. 데이터의 종류
#### 정규화를 해야할 것 : '기온(°C)_seoul', '강수량(mm)_seoul', '습도(%)_seoul', '적설(cm)_seoul', '기온(°C)_busan', '강수량(mm)_busan', '습도(%)_busan', '적설(cm)_busan', 'weekday', 'hour',  '노출(분)','quater', 판매단가

#### 처리가 필요(one-hot) :  '상품군',  'time'

#### 그대로 사용 :  'pmWarning_seoul', 'pmWarning_busan', '휴일', 

#### 정답 : 취급액

#### standard_scalar_list

In [62]:
from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()

standard_scalar_list = ['기온(°C)_seoul', '기온(°C)_seoul',
                                                         '강수량(mm)_seoul', '습도(%)_seoul', '적설(cm)_seoul',
                                                         '기온(°C)_busan', '강수량(mm)_busan', '습도(%)_busan',
                                                         '적설(cm)_busan', 'weekday', 'hour', '노출(분)','quater', '판매단가']

data_use_fit[standard_scalar_list] = std_scaler.fit_transform(pd.DataFrame(data_use[standard_scalar_list]))
data_use_fit

,노출(분),상품군,판매단가,취급액,휴일,weekday,hour,기온(°C)_seoul,강수량(mm)_seoul,습도(%)_seoul,적설(cm)_seoul,기온(°C)_busan,강수량(mm)_busan,습도(%)_busan,적설(cm)_busan,pmWarning_seoul,pmWarning_busan,quater
0,-0.123014,의류,-0.585286,2099000.0,True,-1.001102,-1.254961,-2.123760,-0.126619,0.240774,-0.064209,-2.306757,-0.152123,-0.872553,-0.00896,False,False,-1.360118
1,-0.123014,의류,-0.585286,3262000.0,True,-1.001102,-1.254961,-2.123760,-0.126619,0.240774,-0.064209,-2.306757,-0.152123,-0.872553,-0.00896,False,False,-1.360118
2,-0.123014,의류,-0.585286,6672000.0,True,-1.001102,-1.254961,-2.123760,-0.126619,0.240774,-0.064209,-2.306757,-0.152123,-0.872553,-0.00896,False,False,-1.360118
3,-0.123014,속옷,-0.559173,6819000.0,True,-1.001102,-1.103915,-2.104648,-0.126619,0.141444,-0.064209,-2.319626,-0.152123,-0.636707,-0.00896,False,False,-1.360118
4,-0.123014,속옷,-0.559173,15689000.0,True,-1.001102,-1.103915,-2.104648,-0.126619,0.141444,-0.064209,-2.319626,-0.152123,-0.636707,-0.00896,False,False,-1.360118
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37367,-0.123014,주방,-0.423823,2328000.0,False,-1.001102,1.312814,-2.075980,-0.126619,-0.504205,-0.064209,-2.383969,-0.152123,-1.815935,-0.00896,False,False,1.376864
37368,-0.123014,주방,-0.437495,10157000.0,False,-1.001102,1.312814,-2.075980,-0.126619,-0.504205,-0.064209,-2.383969,-0.152123,-1.815935,-0.00896,False,False,1.376864
37369,-0.123014,주방,-0.410151,104392000.0,True,-0.502466,-2.161234,-1.989976,-0.126619,-0.851861,-0.064209,-2.409706,-0.152123,-1.863104,-0.00896,False,False,-1.360118
37370,-0.123014,주방,-0.423823,13765000.0,True,-0.502466,-2.161234,-1.989976,-0.126619,-0.851861,-0.064209,-2.409706,-0.152123,-1.863104,-0.00896,False,False,-1.360118
37371,-0.123014,주방,-0.437495,46608000.0,True,-0.502466,-2.161234,-1.989976,-0.126619,-0.851861,-0.064209,-2.409706,-0.152123,-1.863104,-0.00896,False,False,-1.360118

In [63]:
from sklearn.preprocessing import LabelEncoder
one_hot_list = [ '상품군']
encoder = LabelEncoder()
data_use_fit[one_hot_list]=encoder.fit_transform(data_use[one_hot_list])/10

C:\Users\dlwlg\Anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [64]:
data_use_fit

,노출(분),상품군,판매단가,취급액,휴일,weekday,hour,기온(°C)_seoul,강수량(mm)_seoul,습도(%)_seoul,적설(cm)_seoul,기온(°C)_busan,강수량(mm)_busan,습도(%)_busan,적설(cm)_busan,pmWarning_seoul,pmWarning_busan,quater
0,-0.123014,0.6,-0.585286,2099000.0,True,-1.001102,-1.254961,-2.123760,-0.126619,0.240774,-0.064209,-2.306757,-0.152123,-0.872553,-0.00896,False,False,-1.360118
1,-0.123014,0.6,-0.585286,3262000.0,True,-1.001102,-1.254961,-2.123760,-0.126619,0.240774,-0.064209,-2.306757,-0.152123,-0.872553,-0.00896,False,False,-1.360118
2,-0.123014,0.6,-0.585286,6672000.0,True,-1.001102,-1.254961,-2.123760,-0.126619,0.240774,-0.064209,-2.306757,-0.152123,-0.872553,-0.00896,False,False,-1.360118
3,-0.123014,0.5,-0.559173,6819000.0,True,-1.001102,-1.103915,-2.104648,-0.126619,0.141444,-0.064209,-2.319626,-0.152123,-0.636707,-0.00896,False,False,-1.360118
4,-0.123014,0.5,-0.559173,15689000.0,True,-1.001102,-1.103915,-2.104648,-0.126619,0.141444,-0.064209,-2.319626,-0.152123,-0.636707,-0.00896,False,False,-1.360118
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37367,-0.123014,0.9,-0.423823,2328000.0,False,-1.001102,1.312814,-2.075980,-0.126619,-0.504205,-0.064209,-2.383969,-0.152123,-1.815935,-0.00896,False,False,1.376864
37368,-0.123014,0.9,-0.437495,10157000.0,False,-1.001102,1.312814,-2.075980,-0.126619,-0.504205,-0.064209,-2.383969,-0.152123,-1.815935,-0.00896,False,False,1.376864
37369,-0.123014,0.9,-0.410151,104392000.0,True,-0.502466,-2.161234,-1.989976,-0.126619,-0.851861,-0.064209,-2.409706,-0.152123,-1.863104,-0.00896,False,False,-1.360118
37370,-0.123014,0.9,-0.423823,13765000.0,True,-0.502466,-2.161234,-1.989976,-0.126619,-0.851861,-0.064209,-2.409706,-0.152123,-1.863104,-0.00896,False,False,-1.360118
37371,-0.123014,0.9,-0.437495,46608000.0,True,-0.502466,-2.161234,-1.989976,-0.126619,-0.851861,-0.064209,-2.409706,-0.152123,-1.863104,-0.00896,False,False,-1.360118

In [65]:
data_use_fit.to_csv('data/train_set/3.data_normalize.csv',index = False)